[package]
name = "AdventOfCode2020"
version = "0.1.0"
authors = ["Richard Cheney <cheneysan@gmail.com>"]
edition = "2018"

#[[bin]]
#name = "day1"
#path = "src/bin/day1.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
regex = "1.4.5"
lazy_static = "1.4.0"
